name: maven-deploy
on: [push]
jobs:
  maven-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: github
      - run: mvn clean deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
