name: maven-site-deploy
on:
  schedule:
    - cron: '11 0 9 * *'
jobs:
  maven-site-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: github
      - run: mvn clean install
      - run: mvn site-deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
