name: maven-pre-site
on:
  schedule:
    - cron: '11 0 20-26 * *'
jobs:
  maven-pre-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: github
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-pre-site
          restore-keys: maven-repo-
      - uses: actions/cache@v3
        with:
          path: ~/.cache/babzel
          key: opennlp-model-cache-${{ github.run_id }}
          restore-keys: opennlp-model-cache-
      - run: mvn clean install
      - run: mvn -Dmax.exec.minutes=333 pre-site
