name: maven-pre-site
on:
  schedule:
    - cron: '11 0 14,15,16,17 * *'
jobs:
  maven-pre-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: github
      - uses: actions/cache@v3
        with:
          path: ~/.cache/babzel
          key: opennlp-model-cache
      - run: mvn clean install
      - run: mvn -Dmax.exec.hours=4 pre-site
