name: maven-deploy
on: [push]
jobs:
  maven-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          server-id: github
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-repo-${{ hashFiles('**/pom.xml') }}-deploy
          restore-keys: maven-repo
      - run: mvn clean install
      - uses: actions/delete-package-versions@v3
        with:
          package-name: 'org.babzel.babzel'
          min-versions-to-keep: 0
      - uses: actions/delete-package-versions@v3
        with:
          package-name: 'org.babzel.babzel-tools'
          min-versions-to-keep: 0
      - uses: actions/delete-package-versions@v3
        with:
          package-name: 'org.babzel.babzel-tools-simple'
          min-versions-to-keep: 0
      - uses: actions/delete-package-versions@v3
        with:
          package-name: 'org.babzel.babzel-tools-lucene'
          min-versions-to-keep: 0
      - run: mvn deploy
        env:
          GITHUB_TOKEN: ${{ github.token }}
