name: maven-site-deploy
on:
  schedule:
    - cron: '5,15,25,35,45,55 * 13 * *'
jobs:
  maven-site-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
          server-id: github
      - uses: actions/cache@v3
        with:
          path: ~/test-cache
          key: t-cache
      - run: jshell ./src/site/test-cache.jsh
